[package]
name = "terminal_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.4"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls" ] }